services:
  photosite_server:
    container_name: photosite_server
    build:
      context: server
      dockerfile: dev.Dockerfile
    volumes:
      - ./server:/server
    env_file:
      - ./.env
    expose:
      - 3001
    ports:
      - 3001:3001
    networks:
      - photosite_db_net
      - local-nginx-net

    command: npm run dev

  photsite_client:
    container_name: photosite_client
    build:
      context: client
      dockerfile: Dockerfile.dev
    volumes:
      - ./client:/client
      #-  /client/node_modules
    expose:
      - 3000
    ports:
      - 3000:3000
    networks:
      - local-nginx-net
    command: npm run dev

  photosite_db:
    container_name: photosite_db
    image: postgres
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pg-data:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - ${POSTGRES_PORT}:5432
    networks:
      - photosite_db_net
#
networks:
  local-nginx-net:
    external: true
  photosite_db_net:

volumes:
  pg-data:
