apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  local:
    push: true
    # useDockerCLI: false
    # useBuildkit: true
  artifacts:
    - image: drososdro/photo-site-client
      context: client
      docker:
        dockerfile: Dockerfile.dev
      sync:
        manual:
          - src: "src/**/*"
            dest: .
