import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";

//WARN: need to change this to mathc the app
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

//WARN: suppressHydrationWarning need to add this on html

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        />
        {children}
      </body>
    </html>
  );
}
